# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-06 16:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carpetas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_ingreso', models.DateField(default=django.utils.timezone.now)),
                ('estado', models.BooleanField(default=False)),
                ('media', models.FileField(blank=True, null=True, upload_to='Mi Carpeta/')),
            ],
            options={
                'verbose_name_plural': 'Carpetas',
            },
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(blank=True, max_length=255, null=True)),
                ('responsable', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_de_ingreso', models.DateField(default=django.utils.timezone.now)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('codigo_postal', models.CharField(blank=True, max_length=25, null=True)),
                ('localidad', models.CharField(blank=True, max_length=255, null=True)),
                ('cuit', models.CharField(blank=True, max_length=13, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('provincia', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Facturas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_de_empresa', models.IntegerField(null=True)),
                ('factura_para', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('cantidad', models.IntegerField(null=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('precio_unitario', models.IntegerField(null=True)),
                ('importe', models.IntegerField(null=True)),
                ('subtotal', models.IntegerField(null=True)),
                ('total', models.IntegerField(null=True)),
                ('observaciones', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Facturas',
            },
        ),
        migrations.CreateModel(
            name='Liquidacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_del_empleado', models.IntegerField(null=True)),
                ('codigo_del_servicio', models.IntegerField(null=True)),
                ('codigo_de_cliente', models.IntegerField(null=True)),
                ('horas', models.IntegerField(null=True)),
                ('valor_hora', models.IntegerField(null=True)),
                ('salario', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Liquidaciones',
            },
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_de_empresa', models.IntegerField(null=True)),
                ('fecha_pago', models.DateField(default=django.utils.timezone.now)),
                ('importe_pago', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Pagos',
            },
        ),
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presupuesto', models.IntegerField(null=True)),
                ('codigo_de_empresa', models.IntegerField(null=True)),
                ('codigo_de_servicio', models.IntegerField(null=True)),
                ('categoria_empleado', models.IntegerField(null=True)),
                ('cantidad_de_empleados', models.IntegerField(null=True)),
                ('codigo_de_empleados', models.IntegerField(null=True)),
                ('cantidad_de_horas', models.IntegerField(null=True)),
                ('valor_hora', models.IntegerField(null=True)),
                ('subtotal', models.IntegerField(null=True)),
                ('importe_total', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Presupuestos',
            },
        ),
        migrations.CreateModel(
            name='Tareas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_ingreso', models.DateField(default=django.utils.timezone.now)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Tareas',
            },
        ),
    ]
