# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-11 01:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carpetas', '0002_auto_20180706_2003'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientes',
            options={'verbose_name_plural': 'Clientes'},
        ),
        migrations.RenameField(
            model_name='carpetas',
            old_name='estado',
            new_name='finalizada',
        ),
    ]
