# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-11 17:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carpetas', '0003_auto_20180710_2238'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tareas',
        ),
    ]
