# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-14 19:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carpetas', '0005_auto_20180714_1611'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gestion',
            options={'verbose_name_plural': 'Gestion'},
        ),
    ]
