# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-28 21:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carpetas', '0006_auto_20180714_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='gestion',
            name='productor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carpetas.Clientes'),
        ),
    ]
