# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-29 00:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carpetas', '0007_gestion_productor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clientes',
            new_name='Productores',
        ),
        migrations.AlterModelOptions(
            name='gestion',
            options={'ordering': ['apellido_y_nombre'], 'verbose_name_plural': 'Gestion'},
        ),
        migrations.AlterModelOptions(
            name='productores',
            options={'ordering': ['razon_social'], 'verbose_name_plural': 'Clientes'},
        ),
        migrations.RenameField(
            model_name='gestion',
            old_name='nombre',
            new_name='apellido_y_nombre',
        ),
    ]
