# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-29 00:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carpetas', '0009_auto_20180728_2140'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productores',
            options={'verbose_name_plural': 'Productores'},
        ),
    ]
