# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-29 00:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tareas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, help_text='Escribe el t\xedtulo...', max_length=125, null=True)),
                ('fecha_ingreso', models.DateField(default=django.utils.timezone.now)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('finalizada', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['titulo'],
                'verbose_name_plural': 'Tareas',
            },
        ),
    ]
